### ISSUE TITLE
[Bug]: 'prisma invocation: Unique constraint failed' when verifying email after registering with Reddit

### ISSUE THREAD

**Issue by loftshed** [civitai/civitai#112]
### What happened?

When signing up to Civitai using a Reddit account, an error is thrown if the email address provided for Civitai registration is the same as the email that was used to register for the Reddit account.

### Steps to reproduce the problem

-Click burger menu
-Sign in/sign up
-Register with Reddit account
-When validating username/email use same email as for Reddit account

### What should have happened?

Username/Email validation form allows you to use the same email address that you used to register your SSO account

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by JustMaier** [comment]
Ok, we've made it so that if you login with an oAuth provider that verifies email addresses (Google, GitHub), then it will automatically connect to the account with that same email address.

As for Reddit and Discord, we can't safely automatically connect the accounts with the same email address because both of them allow you to create and connect an account using an unverified email address. This could lead to someone making a dummy account on one of those services using another user's email address and then taking over that user's account by picking that as an Auth option on Civitai.

So, if you want to connect a Reddit account or Discord account to a Civitai account that already exists with the same email address, please login with the provider you used to setup that account and then connect those services from your account page.

---

Sorry that this doesn't directly solve your problem, but until we build an email verification system (which would require us to actually start sending emails), we can't securely enable automatically connecting Reddit accounts to existing Civitai accounts with the same email address.
