### ISSUE TITLE
[Bug]: Image Api nsfw Query Parameters error

### ISSUE THREAD

**Issue by sunnyark** [civitai/civitai#1224]
### What happened?

The NSFW-related query in the Image API’s query parameters is malfunctioning. 
When the nsfw value is not defined, everything should be returned, but currently only non-nsfw content is being returned.

### Steps to reproduce the problem

The NSFW-related query in the Image API’s query parameters is malfunctioning. 
When the nsfw value is not defined, everything should be returned, but currently only non-nsfw content is being returned.

### What should have happened?

Please explain how the ‘nsfw’ parameter can function correctly.

**Comment by FaultierSP** [comment]
Came to this page to report exactly this problem. :)

I would add that I found no combination that serves both, nsfw + sfw. If the parameter not defined, it returns only sfw.

**Comment by manuelurenah** [comment]
In order to get nsfw results using the public API endpoint, you need to specify a top nsfw level. For example you can query `/api/v1/images?nsfw=Mature` and it will return images with a nsfwLevel up to `Mature`, so that includes `None, Soft and Mature`. If you want to get only nsfw images, then you can pass `nsfw=true`. Hope this helps!
