### ISSUE TITLE
[Bug]: add a new model fails "file _.safetensors could not be found" on Firefox

### ISSUE THREAD

**Issue by Best-by-feb132024** [civitai/civitai#285]
### What happened?

Uploading a lora file always fails when clicking `save`. Website is unable to find the model I uploaded when using Firefox

### Steps to reproduce the problem

1. click `upload a model`
2. Select LORA
3. Create a new version
4. Upload the LORA `.safetensors` file
5. Add required fields for the LORA
6. Click `Save`
7. Get error

### What should have happened?

Model uploads just fine and I can save / publish a draft

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

### Additional information, context and logs

Error message

"Could not save model

An error occurred while saving the model: File NameOfLORA.safetensors could not be found.

Please re-upload."

Worked when I upload on Brave browser instead of Firefox.

**Comment by ffedev** [comment]
Same issue, I tried using a different file and even renaming it the same as the model but I cannot upload any .safetensor file on the site

**Comment by manuelurenah** [comment]
Hey @Best-by-feb132024 @ffedev can you please confirm this is an issue for you still? We did some updates to the uploading system and shouldn't be happening anymore

**Comment by Best-by-feb132024** [comment]
Just tried and same error on firefox. My only guesses might be I'm using incognito/private browsing, or it's a browser extension I am using somehow interfering

**Comment by manuelurenah** [comment]
I think this might be a bug on our end. Would you mind sharing more info? Are you uploading a new model or editing an existing one? Is it just a single version? Are you uploading multiple files along with the main LoRA file? Does uploading anything other than `.safetensors` let you save the model? Did you try saving as draft? All of this is useful to figure out the root cause of the issue. I'd appreciate if you could share it

**Comment by ffedev** [comment]
> Hey @Best-by-feb132024 @ffedev can you please confirm this is an issue for you still? We did some updates to the uploading system and shouldn't be happening anymore

Hi, I "resolved" by uploading it with Chrome. 
I re-tried now with Firefox and got the same error, I re-logged from an incognito window and it worked.

currently I'm running:
ClearURLs, Decentraleyes, Facebook Container, Greasemonkey, Privacy Badger, Privacy Possum, Sponsorblock, uBlock Origin.
while Incognito only had uBlock origin for this test,

my user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0

**Comment by manuelurenah** [comment]
@ffedev All of this is helpful, thank you. If possible, can you try doing that upload again, try to save your model (could be draft), then check your network tab in devtools and see if there's any errors with the request? If there is, please share the details of the error and the payload sent. I've run a couple of tests on my end using firefox and all seems to work fine, that's why I'm asking for all this info cause this seems like a particular issue with you guys

**Comment by Best-by-feb132024** [comment]
@manuelurenah 

Only tried with LORA and `.safetensors` files, but testing with a textual inversion `.bin` file also failed for me just now

it fails whether I upload 1 or multiple, and whether I am creating a new LORA / editing a preexisting one / creating a draft.

I have similar privacy plugins to ffedev, and run a VPN

* Ublock origin
* duckduckgo privacy essentials
* clearURLs
* privacy possom
* decentraleyes
* privacy badger

Firefox version is Ver 110.0
