### ISSUE TITLE
[Bug]: LoRA filenames are not preserved on download links

### ISSUE THREAD

**Issue by PseudoChmod** [civitai/civitai#401]
### What happened?

I've noticed that on a LoRA I've made the downloaded files do not have the same name as the one's that I've uploaded. For example, I have two versions of a LoRA that I made for compatibility purposes, and AnythingV3 version and AOM3 version. The AnythingV3 was uploaded with the name "zoroark_AT3.safetensors" but the downloaded file has the title "zoroarkLora_zoroarkLoraAnythingV3.safetensors." Even stranger is that the "zoroark_AOM3.safetensors" version is only named "zoroarkLora_zoroarkLora.safetensors" with no mention of AOM3 in the filename. This is bad since there's now no way to tell what the second file is based on without context (or reading the metadata). I can only confirm that this occurs on LoRA's, I do not have any models to upload.

I think there should either be an option to use the original file name or enter a new one for downloaded files, and the published name shouldn't be prepended to the downloaded files since that's redundant.

Here's the upload in question: https://civitai.com/models/25485

### Steps to reproduce the problem

1. Create a LoRA.
2. Upload LoRA file(s).
3. Publish.
4. Download LoRA from published page and compare filenames.

### What should have happened?

Downloaded files should have had the original filenames from the uploaded files.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Google Chrome

**Comment by CurtisDS** [comment]
It generates the name based off of the page title and the version title. It takes each title, strips special characters from the titles, limits both in length, and then concatenates them with an underscore. So the file name will look like this: `{PageTitle}_{VersionTitle}.ext`. I haven't figured out the exact rule they use for limiting the length of each title in the file name before the text gets cut off. They seem to use some type of algorithm to try and not cut off either title mid-word. But roughly they start cutting stuff out if your title is over 20 characters... roughly, which for you half of that is getting used up by repeating the model title in the version.

A way to solve this would be to not put the page title in your model version titles. Its redundant anyway and is what is causing your file names to get cut off and be missing important information.

If you chose AT3 and AOM3 as your version names the file names would be "zoroarkLora_at3.safetensors" and "zoroarkLora_aom3.safetensors" respectively.

This is what that would look like:
![image](https://user-images.githubusercontent.com/20732674/229878153-e47217b5-6753-41dc-8a0c-fc66fc6ef7aa.png)

Rather than using a long model version name to inform users that a specific version is compatible with a specific checkpoint, use the "About this version" section to communicate that instead.

**Comment by PseudoChmod** [comment]
Alright, thanks for the explanation. I figured there was some kind of concatenation going on, but it wasn't explained anywhere previously and I didn't want to test it and keep update-bumping my published work. I still think having a way to set a specific name would be easiest to understand, while the concatenation can be used to autofill.

**Comment by manuelurenah** [comment]
Hey @PseudoChmod if you want to the edit the version details, you can click the three dot right next to the version name 
<img width="190" alt="image" src="https://user-images.githubusercontent.com/12631159/233129870-bfd7bdc7-b75d-4745-b1f5-8efe8c7594b6.png">
Alternatively, you can click the Edit link in the details description table and select Edit Version Details option 
<img width="461" alt="image" src="https://user-images.githubusercontent.com/12631159/233130122-5c542378-9c0b-48f8-852e-734c0e236c2d.png">

**Comment by sovos15** [comment]
Closed then?
